INSERT INTO CONTA(PERIODO_BENEFICIO, SALDO, VALOR_APOSENTADORIA) VALUES (15, 10000, 0);
INSERT INTO CONTA(PERIODO_BENEFICIO, SALDO, VALOR_APOSENTADORIA) VALUES (15, 0, 0);

INSERT INTO BENEFICIARIO(CPF, EMAIL, NOME, CONTA_ID) VALUES (12761439740, 'pmonteirorf@email.com', 'Priscilla', 1);
INSERT INTO BENEFICIARIO(CPF, EMAIL, NOME, CONTA_ID) VALUES (08639876053, 'joao@email.com', 'Joao', 2);